In [3]:
import pandas as pd
df = pd.read_excel('data.xlsx', index_col=0)
df.head()

,Артикул,Ссылка на товар,Название,Рейтинг,Количество отзывов,Размеры,Цена,Описание,Продавец,Ссылка на продавца,...,Мех опушки/отделки,Воротник,Плотность синтетического утеплителя,Наименование,Длина изделия по спинке,Состояние товара,Характеристика пух/перо (fill power),Фактура материала,Размер,Рос. размер
0,488386749,https://www.wildberries.ru/catalog/488386749/d...,Пальто длинное оверсайз весна-осень в полоску,4.9,120,"42,44,46,48",4076,Женское пальто из натуральной шерсти — идеальн...,HANBIYKE,https://www.wildberries.ru/seller/1304162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,239833866,https://www.wildberries.ru/catalog/239833866/d...,Пальто шерстяное демисезонное с воротником сто...,4.9,1845,"42,44,46,48,50,52,54",8278,"Окунитесь в стиль и комфорт, выбирая женское п...",CORESSI,https://www.wildberries.ru/seller/26796,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,203138526,https://www.wildberries.ru/catalog/203138526/d...,Пальто классика,4.8,2609,"170-176/46 рф,170-176/48 рф,170-176/50 рф,176-...",9900,Шикарное шерстяное полупальто идеально для нос...,Красный ананас,https://www.wildberries.ru/seller/1316722,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,488387894,https://www.wildberries.ru/catalog/488387894/d...,Пальто весна-осень макси в полоску,4.8,114,"46,44,42,48",4076,Женское пальто из натуральной шерсти — идеальн...,HANBIYKE,https://www.wildberries.ru/seller/1304162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,287700029,https://www.wildberries.ru/catalog/287700029/d...,Пальто шерстяное натуральное,4.8,44,"42,44,46,48,50",11523,Черное пальто женское французского бренда Mais...,Rendez-Vous,https://www.wildberries.ru/seller/528630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
target = df.query("`Страна производства` == 'Россия' and `Рейтинг` >= 4.5 and `Цена` < 10000")
target.to_excel("filtered.xlsx")
target.head()

,Артикул,Ссылка на товар,Название,Рейтинг,Количество отзывов,Размеры,Цена,Описание,Продавец,Ссылка на продавца,...,Мех опушки/отделки,Воротник,Плотность синтетического утеплителя,Наименование,Длина изделия по спинке,Состояние товара,Характеристика пух/перо (fill power),Фактура материала,Размер,Рос. размер
1,239833866,https://www.wildberries.ru/catalog/239833866/d...,Пальто шерстяное демисезонное с воротником сто...,4.9,1845,"42,44,46,48,50,52,54",8278,"Окунитесь в стиль и комфорт, выбирая женское п...",CORESSI,https://www.wildberries.ru/seller/26796,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,288989036,https://www.wildberries.ru/catalog/288989036/d...,Короткое шерстяное пальто,4.6,55,"42,44,46,48,50,52",8417,Черное полупальто женское французского бренда ...,Rendez-Vous,https://www.wildberries.ru/seller/528630,...,NaN,отложной,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,366417625,https://www.wildberries.ru/catalog/366417625/d...,Короткое шерстяное пальто,4.9,17,"42,44,46,48,50,52",8804,Бежевое полупальто женское французского бренда...,Rendez-Vous,https://www.wildberries.ru/seller/528630,...,NaN,отложной,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,277883751,https://www.wildberries.ru/catalog/277883751/d...,Полупальто шерстяное,4.7,31,"44,46,48,42,50,52",8030,Серое полупальто женское французского бренда M...,Rendez-Vous,https://www.wildberries.ru/seller/528630,...,NaN,отложной,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,287694148,https://www.wildberries.ru/catalog/287694148/d...,Полупальто шерстяное,4.9,9,"42,44,46,48,50",8804,Бежевое полупальто женское французского бренда...,Rendez-Vous,https://www.wildberries.ru/seller/528630,...,NaN,отложной,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN